#!/bin/sh

NAME=`hostname`
AMP=/sys/class/leds/amplifier
sed -i -e "s,^zeroconf_name.*$,zeroconf_name \"$NAME\",g" /etc/mpd.conf

if [ -f /srv/etc/config ]; then
	. /srv/etc/config
fi

{
	echo "[`ktstamp -k`] Start alarms $NAME"
	runc add USER=nobody mqttalrm -v 'alarms/+/+'
	runc add USER=nobody mqttoff  -v -r 'off' -s 'timeoff' 'alarms/+/state' 'alarms/+/statetimeoff'
	runc add USER=nobody mqttnow  -v -s '/fmtnow' 'state/+/fmtnow'
	runc add httpd -f -h /usr/share/www -c /etc/httpd.conf
} &

if ! [ -d /srv/music ]; then
	echo "[`ktstamp -k`] mount music"
	# btrfs
	#mount /dev/mmcblk0p2 /srv -osubvol=+dat,ro,discard,ssd_spread
	# regular
	mount /dev/mmcblk0p2 /srv -oro
fi

{
	echo "[`ktstamp -k`] Start musicbox $NAME"
	# play test sound, mainly for initializing the alsa
	# output. This make bcm2835-pcm work properly.

	#echo $TESTENABLE > $AMP/brightness
	#aplay /etc/test.wav
	#echo 0 > $AMP/brightness

	runc add mpd --no-daemon
	runc add ympd -w 81 -u nobody

	sockwait /var/run/avahi-daemon/socket

	echo "[`ktstamp -k`] Start shairport $NAME"
	runc add shairport-sync -a "$NAME" --port=5000

	echo "[`ktstamp -k`] Start uPNP $NAME"
	runc add upmpdcli -f "$NAME" -l 0
} &
