#!/bin/sh
#!/bin/sh

echo "[`ktstamp -k`] Start control"

LED=/sys/class/leds/mcpm
AMP=/sys/class/leds/amplifier

case "$1" in
ctrl)
        while read TIME CODE VALUE; do
	if timeofday 6h45 19h15; then
		TYPE=d
	else
		TYPE=n
	fi
	NUM=1
	# only process keyup
	case "$CODE:$VALUE" in
	KEY_SYSRQ:long)
		poweroff
		;;
	KEY_1:1)
		mplay $NUM playlist z${TYPE}1
		;;
	KEY_2:1)
		mplay $NUM playlist z${TYPE}2
		;;
	KEY_3:1)
		mplay $NUM playlist z${TYPE}3
		;;
	KEY_4:1)
		mplay $NUM playlist z${TYPE}4
		;;
	KEY_5:1)
		mplay $NUM playlist z${TYPE}5
		;;
	*:long)
		mpc -q clear
		# leave qeueue empty
		;;
	esac
        done
        ;;
amp)
	# emit MPD's play state to a (green) led

	echo none > $AMP/trigger
	echo oneshot > $LED/trigger
	echo 255 > $LED/brightness
	sockwait /run/mpd.sock
	mpdstate | while read PROP VALUE; do
	case "$PROP:$VALUE" in
	state:play)
		if timeofday 8h00 19h00; then
			echo timer > $LED/trigger
			echo 150 > $LED/delay_on
			echo 150 > $LED/delay_off
		else
			echo none > $LED/trigger
			echo 255 > $LED/brightness
		fi
		echo 255 > $AMP/brightness
		;;
	state:*)
		echo none > $LED/trigger
		echo 0 > $LED/brightness
		echo 0 > $AMP/brightness
		;;
	esac
	done
	;;
*)
	echo heartbeat > /sys/class/leds/ACT/trigger
	echo 0 > /sys/class/leds/PWR/brightness
	for DEV in /dev/input/event*; do
		runc add inputevent --long=0.35 "$DEV" `readlink -f "$0"` ctrl
	done
	runc add `readlink -f "$0"` amp
	;;
esac

