#!/bin/sh

if [ -z "$1" ] || [ -z "$2" ] ; then
	echo "Wrong arguments" >&2
	exit 1
fi

IFACE="$1"

case "$2" in
up)
	exec udhcpc -i "$IFACE" -f -R
	;;
down)
	pkill -f "udhcp.*$IFACE"
	;;
*)
	exit 1;
	;;
esac
